import { Game, LobbyType } from "../types";

export const mockGamesEIgre: Game[] = [
  {
    gameID: 1,
    lobbyType: LobbyType.eIgre,
    gameName: "Game 1",
    webName: "game-1",
    gameCategory: "#category1",
    gameEnabled: 1,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 1,
    providerName: "Provider 1",
    providerGameID: "provider-game-1",
    lobbySortOrder: 0,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-1",
    thumb: "test-thumb",
  },
  {
    gameID: 2,
    lobbyType: LobbyType.eIgre,
    gameName: "Game 2",
    webName: "game-2",
    gameCategory: "#category2",
    gameEnabled: 0,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 2,
    providerName: "Provider 2",
    providerGameID: "provider-game-2",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-2",
  },
  {
    gameID: 3,
    lobbyType: LobbyType.eIgre,
    gameName: "Game 3",
    webName: "game-3",
    gameCategory: "#category3",
    gameEnabled: 1,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 3,
    providerName: "Provider 3",
    providerGameID: "provider-game-3",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-3",
  },
  {
    gameID: 4,
    lobbyType: LobbyType.eIgre,
    gameName: "Game 4",
    webName: "game-4",
    gameCategory: "#category4",
    gameEnabled: 0,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 4,
    providerName: "Provider 4",
    providerGameID: "provider-game-4",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-4",
  },
];
export const mockGamesCasino: Game[] = [
  {
    gameID: 5,
    lobbyType: LobbyType.liveCasino,
    gameName: "Game 1",
    webName: "game-1",
    gameCategory: "#category1",
    gameEnabled: 1,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 1,
    providerName: "Provider 1",
    providerGameID: "provider-game-1",
    lobbySortOrder: 0,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-1",
  },
  {
    gameID: 6,
    lobbyType: LobbyType.liveCasino,
    gameName: "Game 2",
    webName: "game-2",
    gameCategory: "#category2",
    gameEnabled: 0,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 2,
    providerName: "Provider 2",
    providerGameID: "provider-game-2",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-2",
  },
  {
    gameID: 7,
    lobbyType: LobbyType.liveCasino,
    gameName: "Game 3",
    webName: "game-3",
    gameCategory: "#category3",
    gameEnabled: 1,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 3,
    providerName: "Provider 3",
    providerGameID: "provider-game-3",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-3",
  },
  {
    gameID: 8,
    lobbyType: LobbyType.liveCasino,
    gameName: "Game 4",
    webName: "game-4",
    gameCategory: "#category4",
    gameEnabled: 0,
    napomena: "note",
    freePlaySupport: true,
    mobileSupport: true,
    providerID: 4,
    providerName: "Provider 4",
    providerGameID: "provider-game-4",
    lobbySortOrder: 1,
    gameData1: "data1",
    gameData2: "data2",
    gameProviderWebName: "provider-4",
  },
];
